// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered voice style suggestions based on input text.
 *
 * - suggestVoiceStyle - A function that suggests voice styles for a given text.
 * - SuggestVoiceStyleInput - The input type for the suggestVoiceStyle function.
 * - SuggestVoiceStyleOutput - The return type for the suggestVoiceStyle function.
 */

import {getAI} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestVoiceStyleInputSchema = z.object({
  text: z.string().describe('The text content for which voice style suggestions are needed.'),
});
export type SuggestVoiceStyleInput = z.infer<typeof SuggestVoiceStyleInputSchema>;

const SuggestVoiceStyleOutputSchema = z.object({
  suggestions: z
    .array(z.string())
    .describe('An array of voice style suggestions for the given text.'),
});
export type SuggestVoiceStyleOutput = z.infer<typeof SuggestVoiceStyleOutputSchema>;

export async function suggestVoiceStyle(input: SuggestVoiceStyleInput): Promise<SuggestVoiceStyleOutput> {
  return suggestVoiceStyleFlow(input);
}

const prompt = getAI().definePrompt({
  name: 'suggestVoiceStylePrompt',
  input: {schema: SuggestVoiceStyleInputSchema},
  output: {schema: SuggestVoiceStyleOutputSchema},
  prompt: `You are an AI-powered voice style suggestion tool. Based on the input text, suggest voice styles that would be appropriate for the content.

Text: {{{text}}}

Suggestions:`,
});

const suggestVoiceStyleFlow = getAI().defineFlow(
  {
    name: 'suggestVoiceStyleFlow',
    inputSchema: SuggestVoiceStyleInputSchema,
    outputSchema: SuggestVoiceStyleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
